version: '3.8'

services:
  marketing-agent:
    image: ghcr.io/mrgarbonzo/boardroom-tee-marketing:latest
    container_name: marketing-agent-${CLIENT_ID:-default}
    
    # SecretVM Verifiable Message Signing (production)
    volumes:
      - ./crypto:/app/crypto  # TEE-generated keys
      - ./data:/app/data      # Data persistence
      - ./logs:/app/logs      # Logging
      - ./config:/app/config  # Configuration
    
    ports:
      - "8082:8082"      # Main API
      - "29345:29345"    # Attestation endpoint
    
    environment:
      - DEVELOPMENT_MODE=${DEVELOPMENT_MODE:-true}
      - MOCK_TEE_ATTESTATION=${MOCK_TEE_ATTESTATION:-true}
      - MOCK_LLM_PROCESSING=${MOCK_LLM_PROCESSING:-true}
      - AGENT_TYPE=marketing
      - AGENT_MODEL_NAME=mistralai/Mistral-7B-Instruct-v0.3
      - AGENT_API_PORT=8082
      - AGENT_ATTESTATION_PORT=29345
      - AGENT_MAX_MEMORY_MB=7000
      - CLIENT_ID=${CLIENT_ID:-default}
      - HUB_ENDPOINT=${HUB_ENDPOINT:-http://localhost:8080}
      - HUB_ATTESTATION_ENDPOINT=${HUB_ATTESTATION_ENDPOINT:-http://localhost:29343}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    
    # Resource limits for 7B model
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 8G
        reservations:
          cpus: '1.0'
          memory: 4G
    
    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 90s
    
    restart: unless-stopped
    
    networks:
      - boardroom-network

networks:
  boardroom-network:
    driver: bridge
