version: '3.8'

services:
  boardroom-hub:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/your-org/boardroom-tee-hub:latest
    container_name: boardroom-hub-${CLIENT_ID:-default}
    
    # SecretVM Verifiable Message Signing (production)
    volumes:
      - ./crypto:/app/crypto  # TEE-generated keys
      - ./data:/app/data      # Data persistence
      - ./logs:/app/logs      # Logging
      - ./config:/app/config  # Configuration
    
    ports:
      - "8080:8080"      # Main API
      - "29343:29343"    # Attestation endpoint
    
    environment:
      - DEVELOPMENT_MODE=${DEVELOPMENT_MODE:-true}
      - MOCK_TEE_ATTESTATION=${MOCK_TEE_ATTESTATION:-true}
      - MOCK_LLM_PROCESSING=${MOCK_LLM_PROCESSING:-true}
      - HUB_MODEL_NAME=meta-llama/Llama-3.2-1B-Instruct
      - HUB_MAX_MEMORY_MB=3000
      - HUB_API_PORT=8080
      - HUB_ATTESTATION_PORT=29343
      - CLIENT_ID=${CLIENT_ID:-default}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - FINANCE_ENDPOINT=${FINANCE_ENDPOINT:-http://localhost:8081}
      - MARKETING_ENDPOINT=${MARKETING_ENDPOINT:-http://localhost:8082}
    
    # Resource limits for VM deployment
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4G
        reservations:
          cpus: '1.0'
          memory: 2G
    
    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    restart: unless-stopped
    
    networks:
      - boardroom-network

networks:
  boardroom-network:
    driver: bridge