version: '3.8'

services:
  sales-agent:
    image: spoke-sales-boardroom-tee:latest
    container_name: boardroom-sales-agent
    
    # SecretVM Verifiable Message Signing
    volumes:
      - ./crypto/docker_private_key_ed25519.pem:/app/crypto/privkey.pem
      - ./crypto/docker_public_key_ed25519.pem:/app/crypto/pubkey.pem
      - ./crypto/docker_attestation_ed25519.txt:/app/crypto/quote.txt
      
      # Agent data and configuration
      - ./data:/app/data
      - ./logs:/app/logs
      - ./config:/app/config
    
    ports:
      - "8083:8083"      # Agent API
      - "29346:29343"    # Attestation endpoint
    
    environment:
      - AGENT_TYPE=sales
      - AGENT_CLIENT_ID=${CLIENT_ID}
      - HUB_ENDPOINT=${HUB_ENDPOINT:-https://hub:8080}
      - HUB_ATTESTATION_ENDPOINT=${HUB_ATTESTATION_ENDPOINT:-https://hub:29343}
      - AGENT_LOG_LEVEL=INFO
      - AGENT_API_PORT=8083
      - AGENT_ATTESTATION_PORT=29343
      - SALES_MODEL_PATH=/app/models/sales-llm
    
    # Resource limits for small instance
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 1G
    
    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8083/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    restart: unless-stopped
    
    networks:
      - boardroom-network

networks:
  boardroom-network:
    driver: bridge
    external: true
